### ISSUE TITLE
com.thingclips.sdk.security.EncryptionManager.bdpdqbp

### ISSUE THREAD

**Issue by nntriet** [tuya/tuya-home-android-sdk-sample-kotlin#23]
**Describe the bug**
Hi, I got the error from SDK reported in Firebase Crashlytics (sometimes the app crashes for no reason, then I check the Firebase Crashlytics and get the error as below):

**Expected behavior**
Can you help me check this issue?

**Screenshots**
![minosmartcontrols_arn_issue](https://github.com/tuya/tuya-home-android-sdk-sample-kotlin/assets/51434994/ba028482-991d-4f2c-a120-2e79e22cc1b5)

Signal Catcher (runnable):tid=5 systid=8402 
#00 pc 0x6b1320 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 128) (BuildId: 289d75599f6112d5757113220599e90b)
#01 pc 0x719c70 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 236) (BuildId: 289d75599f6112d5757113220599e90b)
#02 pc 0x7291c8 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 216) (BuildId: 289d75599f6112d5757113220599e90b)
#03 pc 0x374e0c libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*) + 448) (BuildId: 289d75599f6112d5757113220599e90b)
#04 pc 0x7276a8 libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool) + 292) (BuildId: 289d75599f6112d5757113220599e90b)
#05 pc 0x727074 libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 300) (BuildId: 289d75599f6112d5757113220599e90b)
#06 pc 0x6fcfcc libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 184) (BuildId: 289d75599f6112d5757113220599e90b)
#07 pc 0x70973c libart.so (art::SignalCatcher::HandleSigQuit() + 468) (BuildId: 289d75599f6112d5757113220599e90b)
#08 pc 0x57f640 libart.so (art::SignalCatcher::Run(void*) + 268) (BuildId: 289d75599f6112d5757113220599e90b)
#09 pc 0xe5a08 libc.so (__pthread_start(void*) + 208) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#10 pc 0x7f27c libc.so (__start_thread + 68) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)

main (native):tid=1 systid=8003 
#00 pc 0xd0ff8 libc.so (__ioctl + 8) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x87cb8 libc.so (ioctl + 160) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#02 pc 0x5f384 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 284) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#03 pc 0x605e0 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 76) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#04 pc 0x6031c libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 224) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#05 pc 0x57ab8 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 308) (BuildId: e715d326cdaa54d19cd16928aec8d5bc)
#06 pc 0x17995c libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 400) (BuildId: baa1b5dd67c6822bd8df46b9cd7a743f)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.system.keystore2.IKeystoreSecurityLevel$Stub$Proxy.createOperation(IKeystoreSecurityLevel.java:233)
       at android.security.KeyStoreSecurityLevel.createOperation(KeyStoreSecurityLevel.java:81)
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:334)
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:234)
       at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2981)
       at javax.crypto.Cipher.tryCombinations(Cipher.java:2892)
       at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2797)
       at javax.crypto.Cipher.chooseProvider(Cipher.java:774)
       at javax.crypto.Cipher.init(Cipher.java:1289)
       at javax.crypto.Cipher.init(Cipher.java:1224)
       at com.thingclips.sdk.security.EncryptionManager.bdpdqbp(unavailable:20)
       at com.thingclips.sdk.security.EncryptionManager.pdqppqb(unavailable:3)
       at com.thingclips.sdk.security.EncryptionManager.bdpdqbp(unavailable:26)
       at com.thingclips.sdk.security.EncryptionManager.pppbppp(unavailable:1)
       at com.thingclips.sdk.security.EncryptionManager.bppdpdq(unavailable:12)
       at com.thingclips.sdk.security.SecuredPreferenceStore.getString(unavailable:21)
       at com.thingclips.sdk.security.SecuredStore.securityUserKey(unavailable:6)
       at com.thingclips.smart.android.base.mmkv.manager.MMKVManager.<init>(unavailable:9)
       at com.thingclips.smart.android.base.mmkv.manager.MMKVManager.<init>(unavailable:1)
       at com.thingclips.smart.android.base.utils.PreferencesUtil.getMMKVManager(unavailable:99)
       at com.thingclips.smart.android.base.utils.PreferencesUtil.getLong(unavailable)
       at com.thingclips.security.prompt.SecurityPromptImpl.checkPrompt(SecurityPromptImpl.java:37)
       at com.thingclips.security.prompt.SecurityPromptImpl.access$100(SecurityPromptImpl.java)
       at com.thingclips.security.prompt.SecurityPromptImpl$1.lambda$onActivityCreated$0(SecurityPromptImpl.java:2)
       at android.os.MessageQueue.next(MessageQueue.java:408)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8364)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

perfetto_hprof_listener (native):tid=7 systid=8404 
#00 pc 0xd0d18 libc.so (read + 8) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#01 pc 0x1e0f4 libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_34> >(void*) + 264) (BuildId: 796c9c10460500734dd5245b60704e28)
#02 pc 0xe5a08 libc.so (__pthread_start(void*) + 208) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
#03 pc 0x7f27c libc.so (__start_thread + 68) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)

Full log: 
[com.mino.smartcontrols.dev_issue_0e9c9e47f3af9d5ba3401950182cd350_ANR_session_646637FB01D800011F43B71C22CEA451_DNE_0_v2_stacktrace.txt](https://github.com/tuya/tuya-home-android-sdk-sample-kotlin/files/11508834/com.mino.smartcontrols.dev_issue_0e9c9e47f3af9d5ba3401950182cd350_ANR_session_646637FB01D800011F43B71C22CEA451_DNE_0_v2_stacktrace.txt)

**Smartphone (please complete the following information):**
 - Device: Oppo Reno7/F21 Pro
 - OS: Android 13
 - Network: Wifi

**SDK:**
 - Version 5.0.1

Thank you!

**Comment by linhuiluo** [comment]
@nntriet Is this a problem that must occur or an occasional problem? Is it an error reported by this sample or an error reported by the app you developed with your own SDK integration?

**Comment by nntriet** [comment]
@linhuiluo Hi, Thanks for your reply. This is an occasional problem as well as the error reported by the project I'm developing.
Btw, I will close this issue as I think it will be an issue due to conflict between the Tuya SDK and the libs using in my project. I will try removing them but in case this issue recurs we can open it again.
