### ISSUE TITLE
java.lang.NullPointerException with firebase-performance

### ISSUE THREAD

**Issue by Alex9992099300** [tuya/tuya-home-android-sdk-sample-kotlin#25]
**Describe the bug**
EXCEPTION  when add plugin  id("com.google.firebase.firebase-perf")

```
   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.thingclips.smart.p2p.toolkit.api.ILog com.thingclips.smart.p2p.toolkit.api.IBuilder.getILog()' on a null object reference
                 	at com.thingclips.smart.p2p.load.ThingP2PLoadManager.invokeEvent(Unknown Source:2)
                 	at com.thingclips.smart.framework.router.SchemeServiceImpl.sendEvent(SchemeServiceImpl.java:198)
                 	at com.thingclips.smart.api.router.UrlRouter.sendEvent(UrlRouter.java:156)
                 	at com.thingclips.smart.wrapper.api.ThingWrapper.onLogin(ThingWrapper.java:139)
                 	at io.fasthome.sls.App.initReact(App.kt:184)
                 	at io.fasthome.sls.App.onCreate(App.kt:128)
                 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7106)
                 	at android.app.ActivityThread.access$1600(ActivityThread.java:273) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loopOnce(Looper.java:210) 
                 	at android.os.Looper.loop(Looper.java:299) 
                 	at android.app.ActivityThread.main(ActivityThread.java:8337) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037) 
``` 

**To Reproduce**
Happened during open Application

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Note 10Lite
 - OS:  Android 12
 - Network:  Wifi

**SDK:**
    tuya = "5.1.0"
    bizbundle = "5.2.0-11"

**Comment by taojingGino** [comment]
ThingSmartSdk.init(this);
Check if there is initialization before logging in
This problem seems to be due to the plugin not being loaded into
@Alex9992099300

**Comment by Alex9992099300** [comment]
Yes,  FirebaseApp.initializeApp(this) before initialization Tuya fixed it , Thanks

**Comment by zlinoliver** [comment]
@Alex9992099300 thanks for the feedback! As this issue is resolved, will close it now.
