### ISSUE TITLE
Crash: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative

### ISSUE THREAD

**Issue by michael19900101** [tuya/tuya-home-android-sdk-sample-kotlin#45]
No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
2024-09-12 10:28:03.695 11268-11268 AndroidRuntime          com.controlfree.ha.home              D  Shutting down VM
2024-09-12 10:28:03.695 11268-11268 AndroidRuntime          com.controlfree.ha.home              E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.test.home, PID: 11268
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
                                                                                                    	at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
                                                                                                    	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:67)
                                                                                                    	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
                                                                                                    	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:88)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:227)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:65)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:244)
                                                                                                    	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
                                                                                                    	at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.kt:37)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
                                                                                                    	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MRwangqi** [comment]
Please follow the developer documentation to configure your own key  https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj
