### ISSUE TITLE
When i run the home sdk sapmle

### ISSUE THREAD

**Issue by usmansaleem369** [tuya/tuya-home-android-sdk-sample-kotlin#47]
E  FATAL EXCEPTION: main
                                                                                                    Process: com.test007.demo, PID: 17011
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
                                                                                                    	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:67)
                                                                                                    	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
                                                                                                    	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:88)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:230)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:65)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:247)
                                                                                                    	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
                                                                                                    	at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.kt:37)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by cerver1** [comment]
You need to make sure you are following step 3 in the guide. https://developer.tuya.com/en/docs/app-development/
